receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  file:
    path: "${OUTPUT_FILE}"
    format: json
    flush_interval: 100ms

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
